### ISSUE TITLE
DetectFaces throws error

### ISSUE THREAD

**Issue by Goktug** [dchatel/comfyui_facetools#1]
Hi,

Thanks for the plugin. However, it throws an error when I try to use it. 

Could you please take a look?

```
Error occurred when executing DetectFaces:

[ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /home/user/ComfyUI/models/landmarks/fan2_68_landmark.onnx failed:Load model /home/user/ComfyUI/models/landmarks/fan2_68_landmark.onnx failed. File doesn't exist

```

![Screenshot 2024-04-08 at 16 02 40](https://github.com/dchatel/comfyui_facetools/assets/534426/b799316b-c63a-4265-b999-6850a003faef)

**Comment by dchatel** [comment]
check the readme
> Download [bluefoxcreation/FaceAlignment](https://huggingface.co/bluefoxcreation/FaceAlignment) model into ComfyUI/models/landmarks
