### ISSUE TITLE
updated comdy wont load the node :(

### ISSUE THREAD

**Issue by 4lt3r3go** [dchatel/comfyui_facetools#10]
![image](https://github.com/dchatel/comfyui_facetools/assets/44883288/815032fe-8ec7-4354-a762-12bd960b2be8)

 i had to do a fresh install, now i'm unable to get this beautiful nodes back :(

**Comment by 4lt3r3go** [comment]
![image](https://github.com/dchatel/comfyui_facetools/assets/44883288/9e4485a3-0634-48d8-ac6d-411cb4aa7b1b)

**Comment by 4lt3r3go** [comment]
solved by installing insightface-0.7.3-cp311-cp311-win_amd64

**Comment by dchatel** [comment]
I just dropped the requirement from insightface completely. In the future this should not happen anymore.
