### ISSUE TITLE
Yolo doesn't run on GPU with rocm

### ISSUE THREAD

**Issue by kilroythethird** [dchatel/comfyui_facetools#11]
Hey, first of all thanks for this node. It improved  my results noticeable.

On my system the YOLO model runs on CPU by default even if there is a cuda backend available (via rocm).
If possible, please add a `.to'' call after loading the model. This fixes the issue with no downsides as far as i see.

In Models.yolo:
```
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
cls._yolo = cls._yolo.to(device)
```

This might be a theoretical issue for other torch backends but from what i see yolo defaults to CPU for these too, so at least this shouldn't make it worse than it was before.

**Comment by dchatel** [comment]
Done. Thanks. I don't why I haven't set that earlier.
