### ISSUE TITLE
I can‘t connect "load insight face model" to "detect faces (your "align faces")"

### ISSUE THREAD

**Issue by YDTRINLEY** [dchatel/comfyui_facetools#2]
![image](https://github.com/dchatel/comfyui_facetools/assets/61964021/a53b0dbc-b589-4424-9dd9-cb48db99b6b5)
I can't find the other nodes that are more similar with your "load insightface" and "align faces" nodes, hope that I got them right. However, I couldn't connect them together. Could you help with it?
Would you mind share your workflow example in json format (not just pictures)? Because you rename the nodes, it's difficult to find the right nodes.
Thank you.

**Comment by YDTRINLEY** [comment]
Sorry, I forgot I can drag workflow picture into Comfyui.
And I found there are no "align faces node" and "face details node" in the lastest version, but when I roll back to the last one version, no bugs pop up.
Thank you.

**Comment by dchatel** [comment]
The most recent version don't use insightface anymore. It uses yolov instead.

**Comment by ethanfel** [comment]
The issue is that the node setup is quite different between the current version and the example. Maybe just update the example. You've made a very useful node, it definitively deserve more spot light.

**Comment by dchatel** [comment]
I updated the readme, the example image (the workflow is embedded in the image), and added a json workflow corresponding to the image.
