### ISSUE TITLE
Detect face node - mask output.

### ISSUE THREAD

**Issue by ethanfel** [dchatel/comfyui_facetools#6]
Hi, is it possible for the detect mask node to have a input with the full size masks before the crop and warp ?

**Comment by dchatel** [comment]
Like this ?
![image](https://github.com/dchatel/comfyui_facetools/assets/1372055/8dbbee90-cd78-4ad1-9ec4-121a51808b0d)

**Comment by ethanfel** [comment]
Thank you first for the first setup, It's exactly what I needed. 

I didn't think of using the solid mask node !
